### ISSUE TITLE
Database Dump

### ISSUE THREAD

**Issue by benhenryhunter** [BrettMerri/GoBlog#1]
Hey Brett,

My name is Ben, I'm the lead developer at Whiteglove Workshops.

Would you be able to give me a DB dump?  As well as a list of routes and body examples for your API?

Overall the code looks good, I'd just like to mess around.

**Comment by BrettMerri** [comment]
[dump.zip](https://github.com/BrettMerri/GoBlog/files/1399859/dump.zip)

GET:
/api/article/read
/api/article/read/{_id}
/api/user/read
/api/user/read/{_id}

POST:
/api/article/add
```
{
	"title": "title",
	"body": "body",
	"user": {
		"_id": "_id"
	}
}
```

/api/article/delete
```
{
	"_id": "_id"
}
```

/api/user/add
```
{
	"username": "username"
}
```

/api/user/delete
```
{
	"_id": "_id"
}
```

/api/comment/add
```
{
	"body": "body",
	"user": {
		"_id": "_id"
	},
	"article": "_id"
}
```

/api/comment/delete
```
{
	"article": "_id",
	"id": id //This is the incrementing comment id which is pulled from the counter collection
}
```

Now that I look at these, the post body's keys could have been named better but this is what I got so far haha. As of this moment, replying to comments, editing comments, and editing articles hasn't been implemented on the Mongo side. Also, commenting or deleting articles hasn't been implemented on the React side. I'm still working on all of this as you can see...

If you want to mess around with the API use `npm run backend` and go to localhost:3001. Thanks!!! 👍

**Comment by benhenryhunter** [comment]
One thing I want you to think about is if there is a better way to order the comments than by the counter.

**Comment by BrettMerri** [comment]
The counter wasn't there for sorting it was to give each comment a unique ID. I just replaced in my latest commit by giving each new comment its own ObjectId.

/api/comment/delete
```
{
	"article": "59e8d7ad66564e94dd1ec762",
	"_id": "59ea42c510657f1fa841064a"
}
```
